Lab4Proyecto/Lab4Proyecto/Models/Pais.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Lab4Proyecto.Models
{
    public class Pais
    {
        [Display(Name = "Nombre")]
        public string nombre { get; set; }
        [Display(Name = "Faltantes")]
        public List<int> faltantes { get; set; }
        [Display(Name = "Coleccionadas")]
        public List<int> coleccionadas { get; set; }
        [Display(Name = "Cambios")]
        public List<int> cambios { get; set; }

        public string faltantesToString()
        {
            string faltan = "";
            for (int i = 0; i < faltantes.Count; i++)
            {
                faltan += faltantes[i];
                if (i != faltantes.Count - 1)
                {
                    faltan += ", ";
                }
            }

            return faltan;
        }
        public string coleccionadasToString()
        {
            string coleccion = "";
            for (int i = 0; i < coleccionadas.Count; i++)
            {
                coleccion += coleccionadas[i];
                if (i != coleccionadas.Count - 1)
                {
                    coleccion += ", ";
                }
            }

            return coleccion;
        }
        public string cambiosToString()
        {
            string cambio = "";
            for (int i = 0; i < cambios.Count; i++)
            {
                cambio += cambios[i];
                if (i != cambios.Count - 1)
                {
                    cambio += ", ";
                }
            }

            return cambio;
        }
    }
}

Lab4Proyecto/Lab4Proyecto/Controllers/PaisController.cs
using Lab4Proyecto.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab4Proyecto.Controllers
{
    public class PaisController : Controller
    {
        // GET: Pais
        public ActionResult Index()
        {
            List<PaisString> paises = new List<PaisString>();
            foreach (var item in Data.instance.Diccionario1)
            {
                PaisString pais = new PaisString();
                pais.nombre = item.Key;
                pais.faltantes = item.Value.faltantesToString();
                pais.coleccionadas = item.Value.coleccionadasToString();
                pais.cambios = item.Value.cambiosToString();
                paises.Add(pais);
            }
            return View(paises);
        }
        public ActionResult Index2()
        {
            List<Calcomania> calcos = new List<Calcomania>();
            foreach (var item in Data.instance.Diccionario2)
            {
                Calcomania nueva = new Calcomania();
                nueva.nombre = item.Key;
                nueva.disponibilidad = Convert.ToString(item.Value);
                calcos.Add(nueva);
            }
            return View(calcos);

        }
        // GET: Pais/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Pais/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pais/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pais/Edit/5
        public ActionResult Actualizar(string id)
        {
            return View(Data.instance.Diccionario1[id]);
        }

        // POST: Pais/Edit/5
        [HttpPost]
        public ActionResult Actualizar(string id, FormCollection collection)
        {
            try
            {
                bool faltante = false, coleccionada = false;
                int nueva = int.Parse(collection["nombre"]);
                if (Data.instance.Diccionario1[id].faltantes.Count != 0)
                {
                    for (int i = 0; i < Data.instance.Diccionario1[id].faltantes.Count; i++)
                    {
                        if (nueva == Data.instance.Diccionario1[id].faltantes[i])
                        {
                            Data.instance.Diccionario1[id].faltantes.RemoveAt(i);
                            Data.instance.Diccionario1[id].coleccionadas.Add(nueva);
                            faltante = true;
                            break;
                        }                        
                    }
                }

                if (!faltante)
                {
                    for (int j = 0; j < Data.instance.Diccionario1[id].coleccionadas.Count; j++)
                    {
                        if (nueva == Data.instance.Diccionario1[id].coleccionadas[j])
                        {
                            Data.instance.Diccionario1[id].cambios.Add(nueva);
                            coleccionada = true;
                            break;
                        }                        
                    }                    
                }

                if (!faltante && !coleccionada)
                {
                    TempData["alertMessage"] = "El número de calcomania que ingresó no existe";
                    return View();
                }                                                
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pais/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Pais/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CrearPorArchivo()
        {
            return View();
        }

        // POST: Jugador/Create
        [HttpPost]
        public ActionResult CrearPorArchivo(HttpPostedFileBase postedFile)
        {
            try
            {
                string todoeltexto = "";
                string filePath = string.Empty;
                if (postedFile != null)
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    int contLinea = 0;
                    string csvData = System.IO.File.ReadAllText(filePath);
                    Dictionary<string, Pais> lista;

                    Data.instance.Diccionario1 = JsonConvert.DeserializeObject< Dictionary < string,Pais >> (csvData);                                            
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult CrearPorArchivo2()
        {
            return View();
        }

        // POST: Jugador/Create
        [HttpPost]
        public ActionResult CrearPorArchivo2(HttpPostedFileBase postedFile)
        {
            try
            {
                string todoeltexto = "";
                string filePath = string.Empty;
                if (postedFile != null)
                {
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    int contLinea = 0;
                    string csvData = System.IO.File.ReadAllText(filePath);

                    Data.instance.Diccionario2 = JsonConvert.DeserializeObject<Dictionary<string, bool>>(csvData);                                        
                }
                return RedirectToAction("Index2");
            }
            catch
            {
                return View();
            }
        }
    }
}

Lab4Proyecto/Lab4Proyecto/Views/Pais/Actualizar.cshtml
@model Lab4Proyecto.Models.Pais

@{
    ViewBag.Title = "Actualizar";
}

<h2>Actualizar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Ingrese el número de calcomanía que acaba de coleccionar</h4>                
        <div class="form-group">
            @Html.LabelFor(model => model.coleccionadas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al diccionario 1", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Lab4Proyecto/Lab4Proyecto/Views/Pais/CrearPorArchivo.cshtml
@{
    ViewBag.Title = "CrearPorArchivo";
}

<h2>CrearPorArchivo</h2>

@using (Html.BeginForm("CrearPorArchivo", "Pais", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="postedFile" />
    <input type="submit" value="Importar" />
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab4Proyecto/Lab4Proyecto/Views/Pais/CrearPorArchivo2.cshtml
@{
    ViewBag.Title = "CrearPorArchivo2";
}

<h2>CrearPorArchivo2</h2>
@using (Html.BeginForm("CrearPorArchivo2", "Pais", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="postedFile" />
    <input type="submit" value="Importar" />
}


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Lab4Proyecto/Lab4Proyecto/Views/Pais/Index.cshtml
@model IEnumerable<Lab4Proyecto.Models.PaisString>

@{
    ViewBag.Title = "Index";
}

<h2>Diccionario 1</h2>


<p>
    @Html.ActionLink("Crear diccionario 1", "CrearPorArchivo")
     @Html.ActionLink("Ver diccionario 2", "Index2")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>            
            @Html.DisplayNameFor(model => model.faltantes)            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.coleccionadas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cambios)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>        
        <td>
            @Html.DisplayFor(modelItem => item.faltantes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.coleccionadas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cambios)
        </td>
        <td>
            @Html.ActionLink("Actualizar", "Actualizar", new { id=item.nombre})            
        </td>
    </tr>
}

</table>

Lab4Proyecto/Lab4Proyecto/Views/Pais/Index2.cshtml
@model IEnumerable<Lab4Proyecto.Models.Calcomania>

@{
    ViewBag.Title = "Index2";
}

<h2>Diccionario 2</h2>

<p>
    @Html.ActionLink("Crear diccionario 2", "CrearPorArchivo2")
    @Html.ActionLink("Ver diccionario 1", "Index")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.disponibilidad)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.disponibilidad)
        </td>        
    </tr>
}

</table>